name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/libs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: package
          path: build
      - name: Zip package bundle
        run: |
          zip -r ./$GITHUB_SHA.zip ./build/*
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
      - name: Push package to S3
        run: aws s3 cp $GITHUB_SHA.zip s3://${{ secrets.AWS_S3_BUCKET }}
      - name: Deploy package
        run: |
          aws deploy create-deployment \
          --application-name dicorndl-spring-playground \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name dicorndl-spring-playground-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=$GITHUB_SHA.zip
